'use client'

import { useState } from "react"
import { Loader2, Bot, Smile, AlertCircle, Clock, CheckCircle, Sparkles } from "lucide-react"
import { useStore } from "@/lib/useStore"
import { saveAnalysis } from "@/lib/saveAnalysis"
import { toast } from "sonner"

export default function Home() {
  const [text, setText] = useState("")
  const [loading, setLoading] = useState(false)
  const [loadingExample, setLoadingExample] = useState(false)
  const [result, setResult] = useState<number | null>(null)
  const [status, setStatus] = useState("")
  const [platformsLoaded, setPlatformsLoaded] = useState(0)
  const { user } = useStore()

  const platforms = [
    "GPTZero", "OpenAI", "Writer", "QuillBot",
    "Copyleaks", "Sapling", "Grammarly", "ZeroGPT"
  ]

  // Handle AI detection
  const handleDetect = async () => {
    if (!text.trim()) return
    setLoading(true)
    setResult(null)
    setStatus("Analyzing text...")
    setPlatformsLoaded(0)

    try {
      const detectRes = await fetch("/api/detect", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text })
      })

      const { id } = await detectRes.json()

      let retries = 0
      let data
      while (retries < 5) {
        await new Promise(res => setTimeout(res, 2000))
        const queryRes = await fetch("/api/query", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ id })
        })
        data = await queryRes.json()
        if (data.status === "done") break
        retries++
      }

      if (data.status === "done") {
        setResult(data.result)
        setStatus("Analysis completed!")
        setPlatformsLoaded(platforms.length)

        // Save analysis if user is logged in
        if (user) {
          await saveAnalysis({
            type: "detector",
            input_text: text,
            result: String(data.result),
            user,
          })
        }
      } else {
        setStatus("Timeout. Please try again.")
      }
    } catch (error) {
      console.error(error)
      setStatus("Error during detection.")
    } finally {
      setLoading(false)
    }
  }

  // Get result label and icon based on the score
  const getResultInfo = (score: number) => {
    const humanPercent = 100 - score

    if (humanPercent > 75) {
      return {
        icon: <Smile className="text-green-600" />,
        label: "Likely Human",
        color: "bg-green-100 text-green-800",
      }
    }

    if (score > 75) {
      return {
        icon: <Bot className="text-red-600" />,
        label: "Likely AI",
        color: "bg-red-100 text-red-700",
      }
    }

    return {
      icon: <AlertCircle className="text-yellow-500" />,
      label: "Mixed (Human + AI)",
      color: "bg-yellow-100 text-yellow-700",
    }
  }

  // Generate example text
  const generateExampleText = async () => {
    setLoadingExample(true)
    try {
      const res = await fetch('https://baconipsum.com/api/?type=meat-and-filler&paras=2')
      const data = await res.json()
      setText(data.join('\n\n'))
      toast.success("Example text generated!")
    } catch (error) {
      console.error(error)
      toast.error("Error generating example text.")
    } finally {
      setLoadingExample(false)
    }
  }

  const resultInfo = result !== null ? getResultInfo(result) : null

  return (
    <div className="flex flex-col items-center justify-start min-h-screen px-4 py-6 bg-gray-50">
      <div className="w-full max-w-6xl bg-white border border-gray-200 rounded-2xl shadow-2xl p-6 sm:p-8">

        {/* Header */}
        <div className="mb-6 text-center">
          <h1 className="text-3xl sm:text-4xl font-extrabold text-gray-900 flex items-center justify-center gap-2">
            <span className="text-blue-600">🤖</span> AI Text Analyzer
          </h1>
          <p className="text-gray-600 text-sm sm:text-base mt-2 max-w-2xl mx-auto">
            Analyze your text to detect if it was generated by AI or written by a human!
          </p>
          <p className="text-gray-400 text-xs mt-1">* For best results, input texts longer than 200 words.</p>
        </div>

        {/* Textarea */}
        <div className="relative">
          <textarea
            placeholder="Paste or type your text here..."
            rows={8}
            maxLength={3000}
            className="w-full rounded-2xl border border-gray-300 focus:ring-4 focus:ring-blue-300 focus:outline-none p-4 text-gray-700 text-sm resize-none transition shadow-sm bg-gray-100 pr-24"
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
          <div className="absolute bottom-2 right-4 text-xs text-gray-400">
            {text.trim() ? text.trim().split(/\s+/).length : 0}/3000 words
          </div>
        </div>

        {/* Action Buttons */}
        <div className="mt-6 flex flex-col sm:flex-row justify-center gap-4">
          <button
            onClick={handleDetect}
            disabled={loading || !text.trim()}
            className="bg-gradient-to-r from-blue-500 to-indigo-600 hover:from-blue-600 hover:to-indigo-700 text-white font-bold px-6 py-2 rounded-full shadow-lg flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed transition text-sm"
          >
            {loading ? <Loader2 className="animate-spin" size={16} /> : null}
            {loading ? "Analyzing..." : "Detect Text"}
          </button>

          <button
            onClick={generateExampleText}
            disabled={loadingExample}
            className="bg-gradient-to-r from-green-400 to-green-600 hover:from-green-500 hover:to-green-700 text-white font-bold px-6 py-2 rounded-full shadow-lg flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed transition text-sm"
          >
            {loadingExample ? <Loader2 className="animate-spin" size={16} /> : <Sparkles size={16} />}
            {loadingExample ? "Generating..." : "Generate Example"}
          </button>
        </div>

        {/* Platforms progress */}
        <div className="mt-6 grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs text-gray-600">
          {platforms.map((name, i) => (
            <div key={name} className="flex items-center gap-2">
              {loading ? (
                platformsLoaded > i ? (
                  <CheckCircle className="text-green-500 w-4 h-4" />
                ) : (
                  <Loader2 className="text-gray-400 w-4 h-4 animate-spin" />
                )
              ) : (
                platformsLoaded > i ? (
                  <CheckCircle className="text-green-500 w-4 h-4" />
                ) : (
                  <Clock className="text-gray-300 w-4 h-4" />
                )
              )}
              <span>{name}</span>
            </div>
          ))}
        </div>

        {/* Status Message */}
        {status && (
          <p className="mt-4 text-center text-xs text-gray-500 italic">{status}</p>
        )}

        {/* Analysis Result */}
        {!loading && result !== null && (
          <div className="mt-8 space-y-6">

            {/* Legend */}
            <div className="flex justify-center items-center gap-6 mb-2">
              <div className="flex items-center gap-2">
                <div className="w-4 h-4 bg-red-500 rounded-sm"></div>
                <span className="text-xs text-gray-600">AI</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-4 h-4 bg-green-500 rounded-sm"></div>
                <span className="text-xs text-gray-600">Human</span>
              </div>
            </div>

            {/* Result Bar */}
            <div className="w-full bg-gray-200 rounded-full h-5 overflow-hidden flex text-xs font-bold text-white">
              <div
                className="h-full bg-red-500 flex items-center justify-center"
                style={{ width: `${result}%` }}
              >
                {result.toFixed(1)}%
              </div>
              <div
                className="h-full bg-green-500 flex items-center justify-center"
                style={{ width: `${100 - result}%` }}
              >
                {(100 - result).toFixed(1)}%
              </div>
            </div>

            {/* Result Info */}
            <div className={`flex items-center justify-center gap-2 rounded-xl px-4 py-2 ${resultInfo?.color}`}>
              {resultInfo?.icon}
              <span className="font-semibold text-base">{resultInfo?.label}</span>
            </div>

          </div>
        )}

      </div>
    </div>
  )
}
